@startuml
'https://plantuml.com/class-diagram

interface Food{
+ eat();
}

class Hamburger{
+ eat();
}

Hamburger ..|>Food

class RiceNoodle{
+ eat();
}
RiceNoodle ..|>Food

class FoodFactory{
+ {static} getFood(int type)
}

/'依赖'/
FoodFactory ..> Food
FoodFactory ..> RiceNoodle
FoodFactory ..> Hamburger




@enduml