@startuml
'https://plantuml.com/class-diagram

interface Food{
+ eat();
}

class Hamburger{
+ eat();
}

Hamburger ..|>Food

class RiceNoodle{
+ eat();
}
RiceNoodle ..|>Food

interface FoodFactory{
+ {static} getFood()
}

class RiceNoodleFactory{
getFood()
}

RiceNoodleFactory ..|>FoodFactory

class HamburgerFactory{
getFood()
}

HamburgerFactory ..|>FoodFactory

/'依赖'/
HamburgerFactory ..> Hamburger
RiceNoodleFactory ..> RiceNoodle

FoodFactory ..> Food




@enduml