@startuml
'https://plantuml.com/class-diagram

@startuml
'https://plantuml.com/class-diagram

interface Food{
+ eat();
}

class Hamburger{
+ eat();
}

Hamburger ..|>Food

class RiceNoodle{
+ eat();
}
RiceNoodle ..|>Food

interface Drink{
+ drink() void
}

class Cola{
+ drink() void
}

Cola ..|>Drink

class IcpPeak{
+ drink() void
}

IcpPeak ..|>Drink


interface Factory{
+ {static} getFood()
+ {static} getDrink()
}
Factory ..> Food
Factory ..> Drink

class KFCFactory{
+ {static} getFood()
+ {static} getDrink()
}
KFCFactory ..>Hamburger
KFCFactory..>Cola

KFCFactory ..|>Factory

class SanQinFactory{
+ {static} getFood()
+ {static} getDrink()
}

SanQinFactory ..|>Factory
SanQinFactory ..> RiceNoodle
SanQinFactory ..> IcpPeak



@enduml